forge 'http://forge.puppetlabs.com'

mod 'puppetlabs-stdlib', '4.25.1'
mod 'puppet/archive', '3.1.1'
mod 'puppetlabs/apt', '6.0.0'
mod 'puppetlabs/mysql', '6.0.0'
mod 'puppetlabs/inifile', '2.3.0'
mod 'puppetlabs/vcsrepo', '2.3.0'
